package io.getquill.context.jasync

object SqlTypes extends Enumeration {
  type SqlTypes = Value

  val BIT, TINYINT, SMALLINT, INTEGER, BIGINT, FLOAT, REAL, DOUBLE, NUMERIC, DECIMAL, CHAR, VARCHAR, LONGVARCHAR, DATE, TIME, TIMESTAMP, BINARY, VARBINARY, LONGVARBINARY, NULL, ARRAY, BLOB, BOOLEAN, TIME_WITH_TIMEZONE, TIMESTAMP_WITH_TIMEZONE, UUID = Value

}
